### ISSUE TITLE
Missing example on a PVC request and the parameters

### ISSUE THREAD

**Issue by mykaul** [oVirt/csi-driver#21]
It'd be great to document how do I request a PVC using this CSI driver.

**Comment by bennyz** [comment]
We have an example here: https://github.com/oVirt/csi-driver/blob/master/deploy/csi-driver/example/storage-claim.yaml

But yes, we should add it to the README

**Comment by mykaul** [comment]
So I can't choose if I'd like to have a thin or full provisioned disk via the PVC?

**Comment by bennyz** [comment]
This is set on StorageClass level, from[1]
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.ovirt.org
parameters:
  # the name of the oVirt storage domain. "nfs" is just an example.
  storageDomainName: "nfs"
  thinProvisioning: "true"
```

[1] https://github.com/oVirt/csi-driver/blob/master/deploy/csi-driver/010-storageclass.yaml
