### ISSUE TITLE
ovirt authentication ignoring "ovirt_ca_bundle" parameter

### ISSUE THREAD

**Issue by bit4man** [oVirt/csi-driver#52]
In internal/ovirt/ovirt.go the connection is done this way:
``` go
func newOvirtConnection() (*ovirtsdk.Connection, error) {
  ovirtConfig, err := GetOvirtConfig()
  if err != nil {
    return nil, err
  }
  connection, err := ovirtsdk.NewConnectionBuilder().
    URL(ovirtConfig.URL).
    Username(ovirtConfig.Username).
    Password(ovirtConfig.Password).
    CAFile(ovirtConfig.CAFile).
    Insecure(ovirtConfig.Insecure).
    Build()
  if err != nil {
    return nil, err
  }

  return connection, nil

}
```
A valid managed ovirt-secret has the following components:
$ oc get -o yaml secret ovirt-credentials
``` yaml
apiVersion: v1
data:
  ovirt_ca_bundle: LS0tLS1...
  ovirt_cafile: ""
  ovirt_insecure: Zm...
  ovirt_password: cm....
  ovirt_url: aHR....
  ovirt_username: b2N...
```

Which fails as the embedded CA is missing.
